### ISSUE TITLE
Add Universal Module Definition

### ISSUE THREAD

**Issue by stefanjudis** [JedWatson/exenv#1]
I'd like to use this in one of my projects.

My environments are "classic" node and the browser without any module loader ( no browserify ).

Wrapping the module in an UMD would make it possible to use it in both env's.
I can also propose a PR if you like. :)

https://github.com/umdjs/umd

**Comment by stefanjudis** [comment]
:+1:

**Comment by JedWatson** [comment]
@stefanjudis :+1:
