### ISSUE TITLE
using Jsdom causes, Incorrect Execution Environment

### ISSUE THREAD

**Issue by abhirathore2006** [JedWatson/exenv#5]
Hi, i am building a Universal app using react, and the issue is , i have to fake the window object using JSdom that is in return causing incorrect execution environment.

is there any workaround for it ? 

below piece of code exactly determines if code is executing on node server or not, without using window object 
> var isNode=new Function("try {return this===global;}catch(e){return false;}");
> isNode() //true if of node server else false

**Comment by JedWatson** [comment]
Sorry for the delay @abhirathore2006 

I'd prefer not to update this package to resolve that case as it would behave differently from React's implementation, which this is designed to mimic but in an external package.

I'd recommend working around this in your app directly, the source code of this package is very simple and unlikely to change in the future so it should be safe to do so.

Thanks for reporting the behaviour & workaround!
